version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shadowdb:
    image: postgres:latest
    container_name: shadow_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: shadowdb
    ports:
      - "5433:5432" # Expose a different port for shadowdb to avoid conflict
    volumes:
      - shadowdb_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  shadowdb_data:
